# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
      # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 2 1,4,7,10 *'
  push:
       paths:
       - 'code/02_calculate_cog.R'

    #branches: [main, master]
  #pull_request:
    #branches: [main, master]

name: R-run-models1

jobs:
  run-models:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1

      - name: "[Custom block] [macOS] Install spatial libraries"
        if: runner.os == 'macOS'
        run: |
          # conflicts with gfortran from r-lib/actions when linking gcc
          rm '/usr/local/bin/gfortran'
          brew install pkg-config gdal proj geos sqlite3

      - name: Install packages
        run:
          Rscript -e "install.packages(c('remotes','dplyr', 'sf'))"

      - name: Install INLA
        run:
          Rscript -e "install.packages('INLA', repos=c(getOption('repos'), INLA='https://inla.r-inla-download.org/R/testing'), dep=TRUE)"

      - name: Install sdmTMB
        run:
          Rscript -e "remotes::install_github('pbs-assess/sdmTMB')"

      - name: Run SDMs
        run:
          Rscript -e "source('code/02_calculate_cog_a.R')"

      - name: Commit results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git diff-index --quiet HEAD || (git commit -a -m'[bot] update files' --allow-empty && git push -f)

